runtime: full
credentials: 
persistence:
  size: 10GB

image:
  repository: theiaide/theia
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # If not set it will use the default
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  
service:
  type: ClusterIP
  port: 3000

