
# available runtimes: go, python, dart, cpp, java, full
runtime: full

# run htpasswd to generate your value e.g `htpasswd -n $(whoami)`
htpasswd:

persistence:
  size: 10Gi

resources:
  limits:
    cpu: "2"
    memory: 2Gi