
# available runtimes: go, python, dart, cpp, java, full
runtime: full

# run `htpasswd locally -n username` to generate your value
htpasswd: username:$apr1$RYGPGy3r$AyiDAmLULaHNzT58cNy1N.

persistence:
  size: 10Gi

resources:
  limits:
    cpu: "2"
    memory: 2Gi